name: SROIE2019
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit
  - pip
  - opencv
  - pip:
      - vizer
      - yacs
      - visdom
      - sklearn
      - fuzzywuzzy
      - python-Levenshtein
      - regex
      - pytorch-model-summary
      - PyYAML
