name: SROIE2019
channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - cudnn
  - pytorch
  - python=3.7
  - torchvision
  - cudatoolkit
  - pip:
      - yacs
      - regex
      - numpy
      - visdom
      - PyYAML
      - tabulate
      - opencv-python
      - pytorch-model-summary