name: SROIE2019
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pytorch
  - torchvision
  - cudatoolkit
  - cudnn
  - opencv
  - python-Levenshtein
  - scikit-learn
  - fuzzywuzzy
  - pyyaml
  - visdom
  - jsonpatch
  - pytorch-model-summary
  - regex
  - yacs
  - pip:
      - vizer